name: Validate and tests

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Validate with pycodestyle
        run: poetry run pycodestyle --max-line-length 90 lintersmagic.py
      - name: Validate with black
        run: poetry run black --check lintersmagic.py
      - name: Launch tests
        run: poetry run ipython tests/*.py
